### ISSUE TITLE
Towards Stage 4

### ISSUE THREAD

**Issue by hemanth** [js-choi/proposal-function-memo#11]
Below is the checklist, we can use this issue to discuss any questions that arise during each of these stage.

## Stage 4
- [ ] committee approval
- [ ] implement in two browsers
- [ ] significant in-the-field experience
- [ ] merge test262 tests
- [ ] write test262 tests
- [ ] prepare ecma262 PR
- [ ] editor-approved ecma262 PR

## Stage 3
- [ ] committee approval
- [ ] spec editor signoff
- [ ] spec reviewer signoff
- [ ] received developer/implementor feedback

## Stage 2
- [ ] committee approval
- [ ] spec text written
- [ ] spec reviewers selected

## Stage 1
- [x] introduced to TC39 [Presented by @js-choi and @hemanth in the 91st meeting]
- [x] champion(s) identified
- [x] initial explainer
